// <auto-generated />
using System;
using BookIt.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookIt.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260523064208_AddReservasDireccionesYGeografia")]
    partial class AddReservasDireccionesYGeografia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookIt.API.Models.Barrio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartamentoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId", "Nombre")
                        .IsUnique();

                    b.ToTable("Barrios");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000010"),
                            Nombre = "Centro"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000010"),
                            Nombre = "Cordón"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000010"),
                            Nombre = "Ciudad Vieja"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000010"),
                            Nombre = "Palermo"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000010"),
                            Nombre = "Parque Rodó"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000010"),
                            Nombre = "Pocitos"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000010"),
                            Nombre = "Punta Carretas"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000010"),
                            Nombre = "Malvín"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000009"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000010"),
                            Nombre = "Buceo"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000010"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000010"),
                            Nombre = "Punta Gorda"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000011"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000010"),
                            Nombre = "Carrasco"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000012"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000010"),
                            Nombre = "Cerro"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000013"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000010"),
                            Nombre = "Aguada"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000014"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000010"),
                            Nombre = "Reducto"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000015"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000010"),
                            Nombre = "La Blanqueada"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000016"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000010"),
                            Nombre = "Prado"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000017"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000010"),
                            Nombre = "Tajamar"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000018"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000010"),
                            Nombre = "La Comercial"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000019"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000010"),
                            Nombre = "Brazo Oriental"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000020"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000010"),
                            Nombre = "Belvedere"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000021"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000010"),
                            Nombre = "Capurro"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000022"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000010"),
                            Nombre = "Jacinto Vera"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000023"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000010"),
                            Nombre = "Paso de las Duranas"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000024"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000010"),
                            Nombre = "Piedras Blancas"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000025"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000010"),
                            Nombre = "Casavalle"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000101"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Nombre = "Ciudad de la Costa"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000102"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Nombre = "Las Piedras"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000103"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Nombre = "Pando"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000104"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Nombre = "Barros Blancos"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000105"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Nombre = "La Paz"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000106"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Nombre = "Santa Lucía"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000201"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000009"),
                            Nombre = "Maldonado"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000202"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000009"),
                            Nombre = "Punta del Este"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000203"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000009"),
                            Nombre = "San Carlos"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000204"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000009"),
                            Nombre = "Piriápolis"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000205"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000009"),
                            Nombre = "La Barra"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000301"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Nombre = "Artigas"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000302"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Nombre = "Cerro Largo"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000303"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Nombre = "Colonia"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000304"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000005"),
                            Nombre = "Durazno"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000305"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000006"),
                            Nombre = "Flores"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000306"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000007"),
                            Nombre = "Florida"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000307"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000008"),
                            Nombre = "Lavalleja"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000308"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000011"),
                            Nombre = "Paysandú"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000309"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000012"),
                            Nombre = "Río Negro"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000310"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000013"),
                            Nombre = "Rivera"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000311"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000014"),
                            Nombre = "Rocha"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000312"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000015"),
                            Nombre = "Salto"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000313"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000016"),
                            Nombre = "San José"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000314"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000017"),
                            Nombre = "Soriano"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000315"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000018"),
                            Nombre = "Tacuarembó"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000316"),
                            DepartamentoId = new Guid("10000000-0000-0000-0000-000000000019"),
                            Nombre = "Treinta y Tres"
                        });
                });

            modelBuilder.Entity("BookIt.API.Models.Departamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Departamentos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Nombre = "Artigas"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Nombre = "Canelones"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Nombre = "Cerro Largo"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Nombre = "Colonia"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Nombre = "Durazno"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Nombre = "Flores"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Nombre = "Florida"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            Nombre = "Lavalleja"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            Nombre = "Maldonado"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            Nombre = "Montevideo"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            Nombre = "Paysandú"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000012"),
                            Nombre = "Río Negro"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000013"),
                            Nombre = "Rivera"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000014"),
                            Nombre = "Rocha"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000015"),
                            Nombre = "Salto"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000016"),
                            Nombre = "San José"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000017"),
                            Nombre = "Soriano"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000018"),
                            Nombre = "Tacuarembó"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000019"),
                            Nombre = "Treinta y Tres"
                        });
                });

            modelBuilder.Entity("BookIt.API.Models.Direccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BarrioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("DepartamentoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BarrioId");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Direcciones");
                });

            modelBuilder.Entity("BookIt.API.Models.EventCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("EventCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Boda"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Cumpleaños de XV"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Cumpleaños"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Evento corporativo"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Bautismo"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Graduación"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Baile"
                        });
                });

            modelBuilder.Entity("BookIt.API.Models.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Confirmada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("FechaReservaCliente")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("BookIt.API.Models.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int?>("Capacidad")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<Guid?>("DireccionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("PrecioMaximo")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("PrecioMinimo")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("TipoServicio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DireccionId");

                    b.HasIndex("VendorId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("BookIt.API.Models.ServiceEventCategory", b =>
                {
                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventCategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("ServiceId", "EventCategoryId");

                    b.HasIndex("EventCategoryId");

                    b.ToTable("ServiceEventCategories");
                });

            modelBuilder.Entity("BookIt.API.Models.ServiceTag", b =>
                {
                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("ServiceId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ServiceTags");
                });

            modelBuilder.Entity("BookIt.API.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("BookIt.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Activo = true,
                            Email = "admin@bookit.com",
                            FechaActualizacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Admin BookIt",
                            PasswordHash = "$2a$11$Sew5qqQei5YGbBlMLeoty.Jpf69NJxNouPrMT1PqhiWaIRShs3O2.",
                            Rol = "administrador",
                            Telefono = "000-000-0000"
                        });
                });

            modelBuilder.Entity("BookIt.API.Models.Barrio", b =>
                {
                    b.HasOne("BookIt.API.Models.Departamento", "Departamento")
                        .WithMany("Barrios")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("BookIt.API.Models.Direccion", b =>
                {
                    b.HasOne("BookIt.API.Models.Barrio", "Barrio")
                        .WithMany("Direcciones")
                        .HasForeignKey("BarrioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookIt.API.Models.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Barrio");

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("BookIt.API.Models.Reserva", b =>
                {
                    b.HasOne("BookIt.API.Models.Service", "Service")
                        .WithMany("Reservas")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookIt.API.Models.User", "User")
                        .WithMany("Reservas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookIt.API.Models.Service", b =>
                {
                    b.HasOne("BookIt.API.Models.Direccion", "DireccionCompleta")
                        .WithMany("Services")
                        .HasForeignKey("DireccionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BookIt.API.Models.User", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DireccionCompleta");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("BookIt.API.Models.ServiceEventCategory", b =>
                {
                    b.HasOne("BookIt.API.Models.EventCategory", "EventCategory")
                        .WithMany("ServiceEventCategories")
                        .HasForeignKey("EventCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookIt.API.Models.Service", "Service")
                        .WithMany("ServiceEventCategories")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventCategory");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("BookIt.API.Models.ServiceTag", b =>
                {
                    b.HasOne("BookIt.API.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookIt.API.Models.Tag", "Tag")
                        .WithMany("ServiceTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("BookIt.API.Models.Barrio", b =>
                {
                    b.Navigation("Direcciones");
                });

            modelBuilder.Entity("BookIt.API.Models.Departamento", b =>
                {
                    b.Navigation("Barrios");
                });

            modelBuilder.Entity("BookIt.API.Models.Direccion", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("BookIt.API.Models.EventCategory", b =>
                {
                    b.Navigation("ServiceEventCategories");
                });

            modelBuilder.Entity("BookIt.API.Models.Service", b =>
                {
                    b.Navigation("Reservas");

                    b.Navigation("ServiceEventCategories");
                });

            modelBuilder.Entity("BookIt.API.Models.Tag", b =>
                {
                    b.Navigation("ServiceTags");
                });

            modelBuilder.Entity("BookIt.API.Models.User", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
