@BookIt_API_HostAddress = https://localhost:7213

### Registro de usuario
POST {{BookIt_API_HostAddress}}/auth/register
Accept: application/json
Content-Type: application/json

{
  "nombre": "Juan Pérez",
  "telefono": "011-1234-5678",
  "email": "juan@example.com",
  "password": "Password123!",
  "rol": "usuario"
}

###

### Login de usuario
POST {{BookIt_API_HostAddress}}/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "juan@example.com",
  "password": "Password123!"
}

###

### Listar usuarios (requiere token JWT)
@token = <ingrese-su-token-aqui>

GET {{BookIt_API_HostAddress}}/users
Accept: application/json
Authorization: Bearer {{token}}

###

